name: Functional Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  functional-tests:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
        
    - name: Restore dependencies
      run: dotnet restore ProxyServerSolution.sln
      
    - name: Build solution
      run: dotnet build ProxyServerSolution.sln --no-restore --configuration Release
      
    - name: Run functional tests
      run: dotnet test ProxyServer.FunctionalTests/ProxyServer.FunctionalTests.csproj --no-build --configuration Release --verbosity normal
      
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: |
          ProxyServer.FunctionalTests/TestResults/
          **/*.trx
